"""initial_migration

Revision ID: 71e1f609f648
Revises: 
Create Date: 2026-01-17 20:30:46.766124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e1f609f648'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribution_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contribution_limits_year'))

    op.drop_table('contribution_limits')
    with op.batch_alter_table('financial_plans', schema=None) as batch_op:
        batch_op.drop_column('employer_match_enabled')
        batch_op.drop_column('user_annual_salary')
        batch_op.drop_column('employer_match_cap')
        batch_op.drop_column('employer_match_percentage')

    with op.batch_alter_table('financial_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_snapshots', schema=None) as batch_op:
        batch_op.drop_column('age')

    with op.batch_alter_table('financial_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_match_percentage', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True))
        batch_op.add_column(sa.Column('employer_match_cap', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True))
        batch_op.add_column(sa.Column('user_annual_salary', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True))
        batch_op.add_column(sa.Column('employer_match_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))

    op.create_table('contribution_limits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('account_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('limit_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('age_requirement', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'account_type', 'limit_type', name=op.f('uq_year_account_limit'))
    )
    with op.batch_alter_table('contribution_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contribution_limits_year'), ['year'], unique=False)

    # ### end Alembic commands ###
