"""Update financial plans with detailed fields

Revision ID: ba1376118f40
Revises: 1dcee73adf29
Create Date: 2025-12-28 15:26:11.785649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1376118f40'
down_revision = '1dcee73adf29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('cash_value', sa.Float(), nullable=False),
    sa.Column('monthly_contribution', sa.Float(), nullable=False),
    sa.Column('total_contribution_amount', sa.Float(), nullable=False),
    sa.Column('years_to_contribute', sa.Integer(), nullable=False),
    sa.Column('income_start_age', sa.Integer(), nullable=True),
    sa.Column('income_end_age', sa.Integer(), nullable=True),
    sa.Column('user_current_age', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_plans_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_plans_user_id'))

    op.drop_table('financial_plans')
    # ### end Alembic commands ###
